//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admission.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int E_Id { get; set; }
        public int E_Year { get; set; }
        public int E_Queno { get; set; }
        public int E_Time { get; set; }
        public int E_Passmark { get; set; }
        public int E_Seat { get; set; }
    }
}
