//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admission.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        public int Q_Id { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public int E_Year { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Q_Body { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Op_1 { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Op_2 { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Op_3 { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Op_4 { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Op_5 { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Q_Answer { get; set; }
    }
}
